function [plot_title, figure_filename] = setupPlotWrap(figure_handle, options_struct, RunDatas, dependent_var, varied_variable_name, legendvars, varargin)
% SETUPPLOTWRAP provides a compact way to feed options from a plot function
% into setupPlot. The options_struct argument should just be the entire
% options struct of the plot function.

arguments
    figure_handle
    options_struct struct
    RunDatas
    dependent_var string
    varied_variable_name string
    legendvars cell
end
arguments (Repeating)
    varargin
end

    varargin = varargin{1};
    options = options_struct;

    %%% Deal with options added for specific plots
    if ~isfield(options,'PlotEvery')
        options.PlotEvery = 1;
    end
    
    
    [plot_title, figure_filename] = setupPlot( figure_handle, RunDatas, ...
        dependent_var, ...
        varied_variable_name, ...
        legendvars, ...
        varargin, ...
        'yLabel', options.yLabel, ...
        'yUnits', options.yUnits, ...
        'xLabel', options.xLabel,...
        'xUnits', options.xUnits,...
        'FontSize', options.FontSize, ...
        'LegendLabels', options.LegendLabels, ...
        'PlotEvery',options.PlotEvery, ...
        'LegendFontSize', options.LegendFontSize,...
        'LegendTitle',options.LegendTitle,...
        'TitleFontSize',options.TitleFontSize,...
        'PlotPadding', options.PlotPadding,...
        'Position', options.Position,...
        'PlotTitle', options.PlotTitle,...
        'yLim',options.yLim,...
        'xLim',options.xLim);
    
end
