function [fitresult, gof] = nonlinear_diffusion_fit(x, y, t, options)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'Non-Linear Diffusion' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jul-2020 08:46:57

arguments
    x double
    y double
    t double
end
arguments
   options.PlotFit logical = 0 
   options.LineWidth double = 1
   options.Piecewise logical = 1
end


%% Fit: 'Non-Linear Diffusion'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.

if options.Piecewise
    ft = fittype('nonlinear_diffusion_equation(x,t,a,x0,A,c)');
else
    ft = fittype( 'real( A * (t)^(1/a) * (1 - x^2/x0^2)^(1/a) + c )', 'independent', 'x', 'dependent', 'y' );
end

opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Robust = 'Bisquare';
opts.Lower = [0 0 0 t 0];
opts.StartPoint = [0.706046088019609 0.5 100 t 0.2769];
opts.Upper = [Inf Inf Inf t 1000000];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'Non-Linear Diffusion' );

if options.PlotFit
    h = plot(x, fitresult(x) , 'LineWidth', options.LineWidth);
    % Label axes
    grid on
end


